{
  "openapi": "3.1.0",
  "x-stoplight": {
    "id": "x0tz82a6vkdlq"
  },
  "info": {
    "title": "DIGDV",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000"
    }
  ],
  "paths": {
    "/api/device/traffic_detector/data/{id}": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "id",
          "in": "path",
          "required": true
        }
      ],
      "get": {
        "summary": "/api/device/traffic_detector/data/{id}",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "x-examples": {
                    "Example 1": {
                      "device_id": "53264f62-d61b-47a7-ac2e-3a2e227c4856",
                      "device_ip": "172.16.252.24",
                      "device_name": "DT1",
                      "last_message_id": "9cf16785-1891-4bf9-af5c-9616334a48b3",
                      "detector_statistics": {
                        "range_start": "2023-11-29T17:59:25+03:00",
                        "range_end": "2023-11-29T18:00:25+03:00",
                        "directions": [
                          {
                            "code": "1",
                            "name": "По ходу",
                            "lanes": [
                              {
                                "lane": {
                                  "code": "4",
                                  "name": "4"
                                },
                                "total_vehicles": 1,
                                "vehicles_flow": [
                                  {
                                    "vehicle_type": {
                                      "code": "class_0",
                                      "name": "Неопознанный тип ТС"
                                    },
                                    "counter": 0
                                  },
                                  {
                                    "vehicle_type": {
                                      "code": "class_2",
                                      "name": "Велосипед"
                                    },
                                    "counter": 0
                                  },
                                  {
                                    "vehicle_type": {
                                      "code": "class_3",
                                      "name": "Мотоцикл"
                                    },
                                    "counter": 0
                                  },
                                  {
                                    "vehicle_type": {
                                      "code": "class_4",
                                      "name": "Автомобиль"
                                    },
                                    "counter": 1
                                  },
                                  {
                                    "vehicle_type": {
                                      "code": "class_5",
                                      "name": "Грузовое транспортное средство"
                                    },
                                    "counter": 0
                                  },
                                  {
                                    "vehicle_type": {
                                      "code": "class_6",
                                      "name": "Грузовой фургон"
                                    },
                                    "counter": 0
                                  },
                                  {
                                    "vehicle_type": {
                                      "code": "class_7",
                                      "name": "Короткий грузовик"
                                    },
                                    "counter": 0
                                  },
                                  {
                                    "vehicle_type": {
                                      "code": "class_8",
                                      "name": "Длинномерный грузовик"
                                    },
                                    "counter": 0
                                  },
                                  {
                                    "vehicle_type": {
                                      "code": "class_1",
                                      "name": "Пешеход"
                                    },
                                    "counter": 0
                                  }
                                ],
                                "vehicle_interval_avg": 0,
                                "vehicle_interval": 0,
                                "speed_avg": 66.959,
                                "speed85_avg": null,
                                "concentration": 0.403
                              }
                            ]
                          }
                        ]
                      }
                    }
                  },
                  "properties": {
                    "device_id": {
                      "type": "string"
                    },
                    "device_ip": {
                      "type": "string"
                    },
                    "device_name": {
                      "type": "string"
                    },
                    "last_message_id": {
                      "type": "string"
                    },
                    "detector_statistics": {
                      "type": "object",
                      "properties": {
                        "range_start": {
                          "type": "string"
                        },
                        "range_end": {
                          "type": "string"
                        },
                        "directions": {
                          "type": "array",
                          "items": {
                            "type": "object",
                            "properties": {
                              "code": {
                                "type": "string"
                              },
                              "name": {
                                "type": "string"
                              },
                              "direction_vehicles": {
                                "type": "integer",
                                "x-stoplight": {
                                  "id": "np874yj9a0o6f"
                                }
                              },
                              "direction_gap_avg": {
                                "type": "number",
                                "x-stoplight": {
                                  "id": "nj8th5gpcty3q"
                                }
                              },
                              "direction_gap_sum": {
                                "type": "number",
                                "x-stoplight": {
                                  "id": "gxsf81osc9z5s"
                                }
                              },
                              "direction_headway_avg": {
                                "type": "number",
                                "x-stoplight": {
                                  "id": "up4xgyht23rbo"
                                }
                              },
                              "direction_headway_sum": {
                                "type": "number",
                                "x-stoplight": {
                                  "id": "k6dkxkbxjtuzp"
                                }
                              },
                              "direction_speed_avg": {
                                "type": "number",
                                "x-stoplight": {
                                  "id": "xl8576wcozxl3"
                                }
                              },
                              "direction_speed85_avg": {
                                "type": "number",
                                "x-stoplight": {
                                  "id": "icxkfr74bw3c7"
                                }
                              },
                              "direction_occupancy_prc": {
                                "type": "number",
                                "x-stoplight": {
                                  "id": "8703plzrz2dl0"
                                }
                              },
                              "direction_occupancy_sum": {
                                "type": "number",
                                "x-stoplight": {
                                  "id": "fksrnz6wi3dnv"
                                }
                              },
                              "lanes": {
                                "type": "array",
                                "items": {
                                  "type": "object",
                                  "properties": {
                                    "lane": {
                                      "$ref": "#/components/schemas/dicti_code_name"
                                    },
                                    "total_vehicles": {
                                      "type": "integer"
                                    },
                                    "vehicles_flow": {
                                      "type": "array",
                                      "items": {
                                        "type": "object",
                                        "properties": {
                                          "vehicle_type": {
                                            "$ref": "#/components/schemas/dicti_code_name"
                                          },
                                          "counter": {
                                            "type": "integer"
                                          }
                                        }
                                      }
                                    },
                                    "vehicle_interval_avg": {
                                      "type": "integer"
                                    },
                                    "vehicle_interval": {
                                      "type": "integer"
                                    },
                                    "speed_avg": {
                                      "type": "number"
                                    },
                                    "speed85_avg": {
                                      "type": "null"
                                    },
                                    "concentration": {
                                      "type": "number"
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "device_id": "string",
                      "device_ip": "string",
                      "device_name": "string",
                      "last_message_id": "string",
                      "detector_statistics": {
                        "range_start": "string",
                        "range_end": "string",
                        "directions": [
                          {
                            "code": "string",
                            "name": "string",
                            "direction_vehicles": 0,
                            "direction_gap_avg": 0,
                            "direction_gap_sum": 0,
                            "direction_headway_avg": 0,
                            "direction_headway_sum": 0,
                            "direction_speed_avg": 0,
                            "direction_speed85_avg": 0,
                            "direction_occupancy_prc": 0,
                            "direction_occupancy_sum": 0,
                            "lanes": [
                              {
                                "lane": {
                                  "code": "string",
                                  "name": "string"
                                },
                                "total_vehicles": 0,
                                "vehicles_flow": [
                                  {
                                    "vehicle_type": {
                                      "code": "string",
                                      "name": "string"
                                    },
                                    "counter": 0
                                  }
                                ],
                                "vehicle_interval_avg": 0,
                                "vehicle_interval": 0,
                                "speed_avg": 0,
                                "speed85_avg": null,
                                "concentration": 0
                              }
                            ]
                          }
                        ]
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-api-device-traffic_detector-data-id",
        "x-stoplight": {
          "id": "meq892vn2idtf"
        },
        "parameters": [
          {
            "schema": {
              "type": "string"
            },
            "in": "query",
            "name": "id",
            "required": true
          }
        ]
      }
    },
    "/api/services/list": {
      "post": {
        "summary": "/api/services/list",
        "operationId": "post-city-services-list",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "object",
                      "x-stoplight": {
                        "id": "peccrn4wbcgum"
                      },
                      "properties": {
                        "id": {
                          "type": "integer",
                          "x-stoplight": {
                            "id": "8t5arzym9a9vz"
                          }
                        },
                        "name": {
                          "type": "string",
                          "x-stoplight": {
                            "id": "3tzq6dp53urvw"
                          }
                        },
                        "state": {
                          "$ref": "#/components/schemas/dicti_code_name",
                          "x-stoplight": {
                            "id": "u9wzmes7l153d"
                          }
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "data": {
                        "id": 0,
                        "name": "string",
                        "state": {
                          "code": "string",
                          "name": "string"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "x-stoplight": {
          "id": "soxnvmxy3nowx"
        },
        "requestBody": {
          "content": {}
        }
      },
      "parameters": []
    },
    "/city/services/{id}/state": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "id",
          "in": "path",
          "required": true
        }
      ],
      "post": {
        "summary": "/city/services/{id}/state",
        "operationId": "post-city-services-id",
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "x-stoplight": {
          "id": "srw2ftjwshqn0"
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "state": {
                    "type": "string",
                    "x-stoplight": {
                      "id": "0vng3mff5kfxe"
                    }
                  }
                }
              },
              "examples": {
                "Example 1": {
                  "value": {
                    "id": 0,
                    "state": "string"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/event/asudd/force_send/closed": {
      "post": {
        "summary": "/api/event/asudd/force_send/closed",
        "operationId": "post-api-event-asudd-force_send-closed",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "x-stoplight": {
                        "id": "yg4kpccjzvv2v"
                      },
                      "type": "array",
                      "items": {
                        "x-stoplight": {
                          "id": "thmje51hzv0ae"
                        },
                        "type": "integer"
                      }
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "data": [
                        0
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "x-stoplight": {
          "id": "j3ugo5f51hy1m"
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "date_start": {
                    "type": "string",
                    "x-stoplight": {
                      "id": "zbry6bs4glqgh"
                    },
                    "format": "date",
                    "deprecated": true
                  },
                  "date_end": {
                    "type": "string",
                    "x-stoplight": {
                      "id": "1g2cnmx65hzg4"
                    },
                    "format": "date",
                    "deprecated": true
                  }
                },
                "required": [
                  "date_start",
                  "date_end"
                ]
              },
              "examples": {
                "Example 1": {
                  "value": {
                    "date_start": "2019-08-24",
                    "date_end": "2019-08-24"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/city/integration/rtcm_inbox/list": {
      "post": {
        "summary": "/city/integration/rtcm_inbox/list",
        "operationId": "post-city-integration-rtcm_inbox-list",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "x-stoplight": {
                        "id": "kphicgaqyxjra"
                      },
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/city-integration-rtcm_inbox",
                        "x-stoplight": {
                          "id": "athf7weamm6y3"
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "data": [
                        {
                          "id": "string",
                          "received_at": "string",
                          "source": {
                            "id": 0,
                            "name": "string",
                            "description": "string"
                          },
                          "data_type": {
                            "code": "string",
                            "name": "string",
                            "description": "string"
                          },
                          "message": "string"
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "x-stoplight": {
          "id": "befj7xw2hkquy"
        }
      },
      "parameters": []
    },
    "/city/integration/rtcm_inbox/{id}": {
      "parameters": [
        {
          "schema": {
            "type": "string"
          },
          "name": "id",
          "in": "path",
          "required": true
        }
      ],
      "get": {
        "summary": "/city/integration/rtcm_inbox/{id}",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "$ref": "#/components/schemas/city-integration-rtcm_inbox",
                      "x-stoplight": {
                        "id": "au9xlk5thcnz1"
                      }
                    }
                  }
                },
                "examples": {
                  "Example 1": {
                    "value": {
                      "data": {
                        "id": "string",
                        "received_at": "string",
                        "source": {
                          "id": 0,
                          "name": "string",
                          "description": "string"
                        },
                        "data_type": {
                          "code": "string",
                          "name": "string",
                          "description": "string"
                        },
                        "message": "string"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "operationId": "get-city-integration-rtcm_inbox-id",
        "x-stoplight": {
          "id": "ifhyh2ct4234m"
        }
      }
    }
  },
  "components": {
    "schemas": {
      "dicti_id_code_name_description": {
        "title": "dicti_id_code_name_description",
        "x-stoplight": {
          "id": "62j4k0snlm3ki"
        },
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "x-stoplight": {
              "id": "ai292axi1sfcz"
            }
          },
          "code": {
            "type": "string",
            "x-stoplight": {
              "id": "4jxkrshkhipye"
            }
          },
          "name": {
            "type": "string",
            "x-stoplight": {
              "id": "s1gy078ezyks1"
            }
          },
          "description": {
            "type": "string",
            "x-stoplight": {
              "id": "19ehlfmq4cgfn"
            }
          }
        },
        "examples": [
          {
            "id": 0,
            "code": "string",
            "name": "string",
            "description": "string"
          }
        ]
      },
      "dicti_code_name_descriprion": {
        "title": "dicti_code_name_descriprion",
        "x-stoplight": {
          "id": "f5cz7mtfrpzdc"
        },
        "type": "object",
        "properties": {
          "code": {
            "type": "string",
            "x-stoplight": {
              "id": "ji870alfyrbph"
            }
          },
          "name": {
            "type": "string",
            "x-stoplight": {
              "id": "stgvwge0nnxde"
            }
          },
          "description": {
            "type": "string",
            "x-stoplight": {
              "id": "zk0ivwqu5ziji"
            }
          }
        },
        "examples": [
          {
            "code": "string",
            "name": "string",
            "description": "string"
          }
        ]
      },
      "dicti_id_name_description": {
        "title": "dicti_id_name_description",
        "x-stoplight": {
          "id": "mz82ti6c06myw"
        },
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "x-stoplight": {
              "id": "14lft6m484way"
            }
          },
          "name": {
            "type": "string",
            "x-stoplight": {
              "id": "iivht608nhamk"
            }
          },
          "description": {
            "type": "string",
            "x-stoplight": {
              "id": "rnykbmmcbr2sz"
            }
          }
        },
        "examples": [
          {
            "id": 0,
            "name": "string",
            "description": "string"
          }
        ]
      },
      "dicti_code_name": {
        "title": "dicti_code_name",
        "x-stoplight": {
          "id": "pzwflkxd5e1nm"
        },
        "type": "object",
        "properties": {
          "code": {
            "type": "string",
            "x-stoplight": {
              "id": "fpjp2gauk2zpl"
            }
          },
          "name": {
            "type": "string",
            "x-stoplight": {
              "id": "9md1ndzfddqfi"
            }
          }
        },
        "examples": [
          {
            "code": "string",
            "name": "string"
          }
        ]
      },
      "dicti_id_name": {
        "title": "dicti_id_name",
        "x-stoplight": {
          "id": "stw4sbpb5pxle"
        },
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "x-stoplight": {
              "id": "wggojydy823hf"
            }
          },
          "name": {
            "type": "string",
            "x-stoplight": {
              "id": "5ncewbyk7s861"
            }
          }
        },
        "examples": [
          {
            "id": 0,
            "name": "string"
          }
        ]
      },
      "dicti_limit": {
        "type": "object",
        "properties": {
          "limit": {
            "type": "integer"
          }
        },
        "x-examples": {
          "Example 1": {
            "limit": 99999
          }
        },
        "examples": [
          {
            "limit": 0
          }
        ]
      },
      "city-integration-rtcm_inbox": {
        "type": "object",
        "x-stoplight": {
          "id": "2503327fd383c"
        },
        "x-examples": {
          "Example 1": {
            "id": "string",
            "received_at": "string",
            "source": {
              "id": 0,
              "name": "string",
              "description": "string"
            },
            "data_type": {
              "code": "string",
              "name": "string",
              "description": "string"
            },
            "message": "string"
          }
        },
        "properties": {
          "id": {
            "type": "string"
          },
          "received_at": {
            "type": "string"
          },
          "source": {
            "$ref": "#/components/schemas/dicti_id_name_description"
          },
          "data_type": {
            "$ref": "#/components/schemas/dicti_code_name_descriprion"
          },
          "message": {
            "type": "string"
          }
        },
        "examples": [
          {
            "id": "string",
            "received_at": "string",
            "source": {
              "id": 0,
              "name": "string",
              "description": "string"
            },
            "data_type": {
              "code": "string",
              "name": "string",
              "description": "string"
            },
            "message": "string"
          }
        ],
        "title": ""
      }
    }
  },
  "tags": [
    {
      "name": "DIGDV"
    }
  ]
}